FROM gettyimages/spark:latest

COPY target/scala-2.12/Sparky-assembly-0.1.0-SNAPSHOT.jar /tmp
COPY deploy-spark-job.sh /tmp
RUN chmod 700 /tmp/deploy-spark-job.sh

ENTRYPOINT /tmp/deploy-spark-job.sh 
RUN /tmp/deploy-spark-job.sh 

